apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mediawiki.fullname" . }}
  labels:
    app: {{ template "mediawiki.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mediawiki.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
          - mountPath: /var/www/html/images
            name: media-wiki-images
          - mountPath: /var/www/data
            name: data
{{- if eq .Values.mountConfig true }}
          - mountPath:  /var/www/html/LocalSettings.php
            subPath: LocalSettings.php
            name: settings
{{- end }}
      initContainers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - 'chmod -R 755 /var/www/html/images; chown -R www-data:www-data /var/www/html/images;'
          volumeMounts:
          - name: media-wiki-images
            mountPath: /var/www/html/images
          securityContext:
            runAsUser: 0
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: data
        awsElasticBlockStore:
          volumeID: "{{ .Values.volumeId }}"
          fsType: ext4
      - name: media-wiki-images
        persistentVolumeClaim:
          claimName: mediawiki
{{- if eq .Values.mountConfig true }}
      - name: settings
        configMap:
          name: {{ template "mediawiki.fullname" . }}
{{- end }}
