kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elasticsearch-hot-2a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
parameters:
  type: gp2
  zones: us-east-2a
  fsType: ext4
