apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.client.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: elasticsearch-client-svc-{{ .Values.environment }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
      nodePort: 30080
    - name: transport
      port: 9300
      targetPort: transport
      nodePort: 30081
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.client.name }}"
    release: {{ .Release.Name }}
  type: NodePort
