apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: elasticsearch-data-svc-{{ .Values.environment }}
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: transport
  selector:
    component: "{{ .Values.data.name }}"
