---
apiVersion: v1
kind: Service
metadata:
  name: {{template "elasticsearch.fullname" . }}-ext-lb
  labels:
    app: {{ template "elasticsearch.fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
{{- if ne .Values.environment "local" }}
    external-dns.alpha.kubernetes.io/hostname: es-logging.{{ .Values.domain }}.{{ .Values.tld }}. 
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
{{- end }}
spec:
  ports:
    - port: 9200
      name: http
      targetPort: 9200
  selector:
    component: "{{ .Values.client.name }}"
{{- if ne .Values.environment "local" }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
{{- if ne .Values.environment "local" }}
  loadBalancerSourceRanges:
{{ toYaml .Values.Whitelist | indent 2 }}
{{- end }}
