apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "kibana.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: kibana-deployment
spec:
  replicas: {{ .Values.kibana_replicaCount }}
  template:
    metadata:
    {{- if .Values.kibana_podAnnotations }}
      annotations:
{{ toYaml .Values.kibana_podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "kibana.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: kibana-log-stack
        image: "{{ .Values.kibana_image.kibana_repository }}:{{ .Values.kibana_image.kibana_tag }}"
        imagePullPolicy: {{ .Values.kibana_image.kibana_pullPolicy }}
        env:
        {{- range $key, $value := .Values.kibana_env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.kibana_service.kibana_internalPort }}
          name: kibana-port
          protocol: TCP
        resources:
{{ toYaml .Values.kibana_resources | indent 10 }}
    {{- if .Values.kibana_affinity }}
      affinity:
{{ toYaml .Values.kibana_affinity | indent 8 }}
    {{- end }}
      nodeSelector:
        cluster-type: default
      tolerations:
{{ toYaml .Values.kibana_tolerations | indent 8 }}
