---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.logstash_inputs }}
  input_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.logstash_filters }}
  filter_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.logstash_outputs }}
  output_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
